# Generated by Django 3.2.5 on 2021-07-23 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oven',
            fields=[
                ('o_num', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('cyclic_hours', models.DurationField()),
                ('temperature', models.FloatField()),
                ('oven', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='OTA.oven')),
            ],
        ),
    ]
